package db_connection

import (
	"database/sql"
)

/*
Допустим у нас есть таблица база данных postgresql с таким выражением:

CREATE TABLE Products (
    id			integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model		varchar(30) NOT NULL,
    company 	varchar(30) NOT NULL,
    price 		integer NOT NULL
);

Опишем здесь подключение к базе данных PostgreSQL, а в других файлах также все возможные SQL-запросы с этой таблицей
*/

func db() {
	// Строка подключения инкапсулирует следующие параметры: user (логин на сервере PostgreSQL),
	// password, dbname (имя базы данных), sslmode (режим работы с SSL)
	connStr := "user=postgres password=mypass dbname=productdb sslmode=disable"
	db, err := sql.Open("postgres", connStr)
	if err != nil {
		panic(err)
	}
	defer db.Close()

}
